---

ansible_host: 192.168.10.7
ansible_become_password: "{{ vault_ansible_become_password }}"

minio_address: 192.168.10.7
minio_access_key: "{{ vault_minio_access_key }}"
minio_secret_key: "{{ vault_minio_secret_key }}"

drone_gitea_server: "{{ vault_drone_gitea_server }}"
drone_gitea_client_id: "{{ vault_drone_gitea_client_id }}"
drone_gitea_client_secret: "{{ vault_drone_gitea_client_secret }}"
drone_user_create: "{{ vault_drone_user_create }}"
drone_server_proxy_host: "{{ vault_drone_server_proxy_host }}"
drone_database_secret: "{{ vault_drone_database_secret }}"
drone_postgres_user: "{{ vault_drone_postgres_user }}"
drone_postgres_password: "{{ vault_drone_postgres_password }}"
drone_rpc_secret: "{{ vault_drone_rpc_secret }}"
drone_cookie_secret: "{{ vault_drone_cookie_secret }}"

gitea_install_lock: "false"
gitea_disable_registration: "false"
gitea_secret_key: "{{ vault_gitea_secret_key }}"
gitea_http_port: 9003
gitea_root_url: "{{ vault_gitea_root_url }}"
gitea_postgres_user: "{{ vault_gitea_postgres_user }}"
gitea_postgres_password: "{{ vault_gitea_postgres_password }}"
gitea_postgres_db: "gitea"

prometheus_scrape_configs: "{{ vault_prometheus_scrape_configs }}"

docker_registry_passwords: "{{ vault_docker_registry_passwords }}"

k3s_master_no_schedule: yes
