proxy_masked_vless_domain: ""
proxy_masked_naive_domain: ""
proxy_masked_trust_domain: ""
proxy_masked_cert_name: "{{ proxy_masked_vless_domain }}"
proxy_masked_email: ""
proxy_masked_nginx_tls_vless_port: 65433
proxy_masked_singbox_vless_ws_path: "" # example "/api/v2/stream/websocket"
proxy_masked_singbox_vless_ws_warp_path: "" # example "/api/v2/stream/websocket-warp"
proxy_masked_singbox_vless_ws_port: 65444
proxy_masked_singbox_vless_ws_warp_port: 65447
proxy_masked_naive_port: 65445
proxy_masked_trusttunnel_port: 65446
proxy_masked_trusttunnel_version: "1.0.13"
# Client config directories
proxy_masked_clients_dir: "/opt/proxy_masked/clients"
proxy_masked_singbox_clients_dir: "{{ proxy_masked_clients_dir }}/singbox"
proxy_masked_vless_links_dir: "{{ proxy_masked_clients_dir }}/vless"
proxy_masked_vless_qr_dir: "{{ proxy_masked_vless_links_dir }}/vless-qr"
proxy_masked_naive_clients_dir: "{{ proxy_masked_clients_dir }}/naive"
proxy_masked_naive_qr_dir: "{{ proxy_masked_naive_clients_dir }}/qr"
proxy_masked_trusttunnel_install_dir: "/opt/trusttunnel"
proxy_masked_screen_site: "http://127.0.0.1:9001"
proxy_masked_clients:
  client1:
    uuid: null
    password: null
proxy_masked_warp_install_dir: "/opt/warp"
proxy_masked_warp_binary_name: "wgcf"
proxy_masked_warp_wgcf_download_url: "https://github.com/ViRb3/wgcf/releases/download/v2.2.30/wgcf_2.2.30_linux_amd64"
proxy_masked_caddy_install_dir: "/opt/proxy_masked/caddy"
proxy_masked_caddy_binary_path: "{{ proxy_masked_caddy_install_dir }}/caddy"
proxy_masked_skip_clients_config: true
