---

- name: "ensure {{ item }} config subdir exists"
  file:
    path: "{{ ansible_user_dir }}/openvpn-configs/{{ item }}"
    state: "directory"
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: false
- name: "render {{ item }} config"
  template:
    src: "client_conf.j2"
    dest: "{{ ansible_user_dir }}/openvpn-configs/{{ item }}/{{ item }}.ovpn"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"
  become: false
- name: easyrsa build-client-full clients nopass
  command:
    cmd: "/usr/share/easy-rsa/easyrsa build-client-full {{ item }} nopass"
    chdir: "/etc/openvpn/easy-rsa"
    creates: "/etc/openvpn/easy-rsa/pki/issued/{{ item }}.crt"
  become: true
- name: "copy files to {{ ansible_user_dir }}/openvpn-configs/{{ item }}/"
  copy:
    src: "/etc/openvpn/easy-rsa/pki/{{ file_item }}"
    dest: "{{ ansible_user_dir }}/openvpn-configs/{{ item }}/{{ file_item | basename }}"
    mode: "0640"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true
  loop:
    - "ca.crt"
    - "ta.key"
    - "issued/{{ item }}.crt"
    - "private/{{ item }}.key"
  loop_control:
    loop_var: "file_item"
  become: true
- name: "archive {{ item }}"
  community.general.archive:
    path: "{{ ansible_user_dir }}/openvpn-configs/{{ item }}"
    dest: "{{ ansible_user_dir }}/openvpn-configs/{{ item }}.zip"
    format: "zip"
  become: false
