---
all:
  children:

    vpn_servers:
      children:
        wireguard:
          hosts:
            rv-fra-wg01:

    home:
      hosts:
        htpc:
      children:
        k3s_cluster:
          hosts:
            rpi4-01:
            rpi3-01:
          children:
            k3s_master:
              hosts:
                rpi4-01:
