---
all:
  hosts:
    localhost:
  vars: {}
  children:
    home:
      hosts:
        htpc:
        rpi4:
    vpn_servers:
      children:
        wireguard:
          hosts:
            rv-fra-wg01:
