---

all:
  children:

    vpn_servers:
      children:
        wireguard:
          hosts:
            rv-fra-oc01:

    home:
      children:
        k3s_cluster:
          hosts: {}
          children:
            k3s_master:
              hosts: {}
        docker:
          hosts:
            htpc:
        nginx:
          hosts:
            htpc:
