---
all:
  children:

    vpn_servers:
      children:
        wireguard:
          hosts:
            rv-fra-wg01:
            rv-fra-wg02:

    home:
      children:
        k3s_cluster:
          hosts:
            rpi4-01:
          children:
            k3s_master:
              hosts:
                rpi4-01:
        docker:
          hosts:
            htpc:
