---

all:
  children:

    vpn_servers:
      children:
        wireguard:
          hosts:
            rv-fra-vpn01:
        vless:
          hosts:
            rv-fra-vpn01:
    home:
      children:
        k3s_cluster:
          hosts: {}
          children:
            k3s_master:
              hosts: {}
        docker:
          hosts:
            hsrv:
