---
all:
  children:

    vpn_servers:
      children:
        wireguard:
          hosts:
            rv-fra-wg02:
        openvpn: {}
        openconnect:
          hosts:
            rv-fra-oc01:

    home:
      children:
        k3s_cluster:
          hosts: {}
          children:
            k3s_master:
              hosts: {}
        docker:
          hosts:
            htpc:
            rv-fra-oc01:
        nginx:
          hosts:
            htpc:
