---
_k3s_bin_uri_slugs:
  x86_64: k3s
  aarch64: k3s-arm64

k3s_bin_uri_slug: "{{ _k3s_bin_uri_slugs[ansible_architecture] }}"
k3s_bin_download_url: "\
  https://github.com/k3s-io/k3s/releases/download/\
  {{ k3s_version }}%2Bk3s1/\
  {{ k3s_bin_uri_slug }}"

_k3s_hash_arch_slugs:
  x86_64: amd64
  aarch64: arm64

k3s_hash_download_url: "\
  https://github.com/k3s-io/k3s/releases/download/v1.23.6%2Bk3s1/\
  sha256sum-{{ _k3s_hash_arch_slugs[ansible_architecture] }}.txt"
