---

k3s_manifests_dir: "{{ k3s_data_dir }}/server/manifests"

_k3s_bin_uri_slugs:
  x86_64: k3s
  aarch64: k3s-arm64

k3s_bin_uri_slug: "{{ _k3s_bin_uri_slugs[ansible_architecture] }}"
k3s_bin_download_url: "\
  https://github.com/k3s-io/k3s/releases/download/\
  {{ k3s_version }}%2Bk3s1/\
  {{ k3s_bin_uri_slug }}"

_k3s_hash_arch_slugs:
  x86_64: amd64
  aarch64: arm64

k3s_node_arch: "{{ _k3s_hash_arch_slugs[ansible_architecture] }}"

k3s_hash_download_url: "\
  https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}%2Bk3s1/\
  sha256sum-{{ k3s_node_arch }}.txt"

k3s_kubectl_download_url: "\
  https://storage.googleapis.com/kubernetes-release/release/\
  {{ k3s_version }}/bin/linux/\
  {{ k3s_node_arch }}/kubectl"

k3s_kubectl_hash_url: "{{ k3s_kubectl_download_url }}.sha256"

k3s_helm_hash_download_url: "\
  https://get.helm.sh/helm-{{ k3s_helm_version }}-linux-{{ k3s_node_arch }}.tar.gz.sha256sum"
k3s_helm_download_url: "\
  https://get.helm.sh/helm-{{ k3s_helm_version }}-linux-{{ k3s_node_arch }}.tar.gz"
