---

drone_project_src: "${HOME}/droneci"
drone_project_name: "droneci"

drone_drone_image_tag: "2-linux-amd64"
drone_postgres_image_tag: "14-bullseye"
drone_redis_image_tag: "6-bullseye"

drone_published_port: 9002
drone_server_proxy_host: "drone.example.com"

drone_docker_runner_deploy: true
drone_docker_runner_image_tag: "1.8-linux-amd64"
drone_docker_runner_name: "default-runner"
drone_docker_runner_capacity: 1

drone_k3s_runner_deploy: true
drone_k3s_runner_namespace: "drone-ci-runtime"
drone_k3s_runner_resource_request_memory: "1GiB"
drone_k3s_runner_resource_request_cpu: "500"
drone_k3s_runner_image_tag: "linux-arm64"
drone_k3s_runner_name: "k3s-runner"
drone_k3s_runner_capacity: 2

drone_user_create: ""

drone_gitea_server: "https://gitea.example.com/"
drone_gitea_client_id: "05136e57d80189bef462"
drone_gitea_client_secret: "7c229228a77d2cbddaa61ddc78d45e"

drone_rpc_secret: "622f160975adc21018f527e4b1d9304a"
drone_cookie_secret: "a51411d003420ef2cd351c0e57ac51ec"

drone_database_secret: "0c549fd39ae397333761d2cb0c53c219"
drone_postgres_user: "postgres"
drone_postgres_password: "postgres"
drone_postgres_db: "drone"
