---

- name: install apt packages
  apt:
    pkg:
      - docker-compose
    state: present
    install_recommends: no
    update_cache: no
  become: true
  ignore_errors: true

- name: mkdir project
  file:
    path: "{{ project_src }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700

- name: Render docker-compose template
  template:
    dest: "{{ project_src }}/docker-compose.yaml"
    src: docker-compose.j2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    validate: "docker-compose -f %s config"
    mode: 0600
  register: compose

- name: Docker-compose stop
  docker_compose:
    project_src: "{{ project_src }}"
    project_name: "{{ project_name }}"
    state: absent
    files:
      - docker-compose.yaml
    remove_orphans: yes
    pull: yes
    restarted: false
  register: output
  when:
    - compose is changed

- name: Docker-compose UP
  docker_compose:
    project_src: "{{ project_src }}"
    project_name: "{{ project_name }}"
    state: present
    files:
      - docker-compose.yaml
    remove_orphans: yes
    pull: no
    restarted: false
  register: output
