---

wireguard_server:
  external_ip: "{{ ansible_host }}"
  interface_name: wg0
  address4: 10.0.0.1
  mask4: 24
  address6: fd42:42:42::1
  mask6: 64
  port: 63665
  private_key: "uNnM5fVgucUlmMOjd0fEno5MCVFAN3UXfNzJzDVKd3E="
  public_key: "jOXlmYQS7L5Mhxi8u0RUGgc1RBfcG7F5ZpN1CoZMd04="

# ( wg genkey | tee private.key | wg pubkey > public.key ) && cat private.key public.key
wireguard_peers:
  - name: client1
    address4: 10.0.0.2
    address6: fd42:42:42::2
    private_key: "8EcjEOsMqKvfk3LsY+kbmppADEEaK0pE6eTOHMTFZHg="
    public_key: "d4sb/aIyAeKWcl7FXyX4HKo9pn0EpiIL5ZAe7A+wLU8="
  - name: client2
    address4: 10.0.0.3
    address6: fd42:42:42::3
    private_key: "wJ8+nmrRWhh8+RcNWzoD52d33qsxpMeePIhI9wQ+GlU="
    public_key: "wFxX9RmYVEc3hwNAhhOACU6x0ynJd8bglvW0P6qTyRk="
