---

openvpn_port: 1194
openvpn_proto: udp
openvpn_dev: tun0
openvpn_server_external_ip: "{{ ansible_host }}"

openvpn_redirect_gateway: true

openvpn_clients:
  - client

openvpn_dns_servers:
  - 94.140.14.14
  - 94.140.15.15

openvpn_subnet:
  network: 10.0.0.0
  mask: 255.255.255.0
