---

- name: helm repo add prometheus-community
  command: >-
    helm repo add prometheus-community
    https://prometheus-community.github.io/helm-charts
  become: false
  when:
   - "'k3s_master' in group_names"

- name: helm install prometheus
  command: >-
    helm upgrade --install prometheus
    prometheus-community/prometheus
    --namespace monitoring --create-namespace
    --set alertmanager.enabled=false
    --set pushgateway.enabled=false
    --set nodeExporter.enabled=false
    --set server.persistentVolume.enabled=false
  become: false
  when:
   - "'k3s_master' in group_names"

- name: helm install prometheus-adapter
  command: >-
    helm upgrade --install prometheus-adapter
    prometheus-community/prometheus-adapter
    --namespace monitoring
    --set prometheus.url=http://prometheus-server
    --set prometheus.port=80
  become: false
  when:
   - "'k3s_master' in group_names"
