- name: Ensure client config dirs exists
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ proxy_masked_clients_dir }}"
    - "{{ proxy_masked_singbox_clients_dir }}"
    - "{{ proxy_masked_vless_links_dir }}"
    - "{{ proxy_masked_vless_qr_dir }}"
    - "{{ proxy_masked_naive_clients_dir }}"
    - "{{ proxy_masked_naive_qr_dir }}"
  when:
    - not proxy_masked_skip_clients_config

- name: Install QR encoder
  apt:
    name: qrencode
    state: present
    update_cache: yes
  when:
    - not proxy_masked_skip_clients_config

- name: Manage masked clients UUID and WS paths
  masked_clients_state:
    clients: "{{ proxy_masked_clients }}"
    force: false
  register: masked_result

- name: Update proxy_masked_clients fact
  set_fact:
    proxy_masked_clients: "{{ masked_result.clients }}"

- name: Generate sing-box client configs for each client
  template:
    src: client.json.j2
    dest: "{{ proxy_masked_singbox_clients_dir }}/{{ item.key }}.json"
    mode: "0644"
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  vars:
    client_name: "{{ item.value.name }}"
    client_uuid: "{{ item.value.uuid }}"
    client_password: "{{ item.value.password }}"
  no_log: true
  when:
    - proxy_masked_vless_domain is defined
    - proxy_masked_vless_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate VLESS direct links
  template:
    src: vless_direct_uri.j2
    dest: "{{ proxy_masked_vless_links_dir }}/{{ item.key }}_direct.txt"
    mode: "0644"
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  vars:
    client_name: "{{ item.value.name }}"
    client_uuid: "{{ item.value.uuid }}"
  no_log: true
  when:
    - proxy_masked_vless_domain is defined
    - proxy_masked_vless_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate VLESS warp links
  template:
    src: vless_warp_uri.j2
    dest: "{{ proxy_masked_vless_links_dir }}/{{ item.key }}_warp.txt"
    mode: "0644"
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  vars:
    client_name: "{{ item.value.name }}"
    client_uuid: "{{ item.value.uuid }}"
  no_log: true
  when:
    - proxy_masked_vless_domain is defined
    - proxy_masked_vless_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate QR for VLESS direct links
  shell: >
    qrencode
    -t png
    -o {{ proxy_masked_vless_qr_dir }}/{{ item.key }}_direct.png
    < {{ proxy_masked_vless_links_dir }}/{{ item.key }}_direct.txt
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  no_log: true
  when:
    - proxy_masked_vless_domain is defined
    - proxy_masked_vless_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate QR for VLESS warp links
  shell: >
    qrencode
    -t png
    -o {{ proxy_masked_vless_qr_dir }}/{{ item.key }}_warp.png
    < {{ proxy_masked_vless_links_dir }}/{{ item.key }}_warp.txt
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  no_log: true
  when:
    - proxy_masked_vless_domain is defined
    - proxy_masked_vless_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate official naive client configs
  template:
    src: naive.json.j2
    dest: "{{ proxy_masked_naive_clients_dir }}/{{ item.key }}.json"
    mode: "0644"
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  vars:
    client_name: "{{ item.value.name }}"
    client_password: "{{ item.value.password }}"
  no_log: true
  when:
    - proxy_masked_naive_domain is defined
    - proxy_masked_naive_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate naive URIs
  template:
    src: naive_uri.j2
    dest: "{{ proxy_masked_naive_clients_dir }}/{{ item.key }}.txt"
    mode: "0644"
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  no_log: true
  vars:
    client_name: "{{ item.value.name }}"
    client_password: "{{ item.value.password }}"
  when:
    - proxy_masked_naive_domain is defined
    - proxy_masked_naive_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate QR for naive URIs
  shell: >
    qrencode
    -t png
    -o {{ proxy_masked_naive_qr_dir }}/{{ item.key }}.png
    < {{ proxy_masked_naive_clients_dir }}/{{ item.key }}.txt
  loop: "{{ proxy_masked_clients | dict2items }}"
  loop_control:
    loop_var: item
  no_log: true
  when:
    - proxy_masked_naive_domain is defined
    - proxy_masked_naive_domain | length > 0
    - not proxy_masked_skip_clients_config

- name: Generate sing-box server config with all clients
  template:
    src: singbox_multi_clients.json.j2
    dest: /etc/sing-box/config.json
  notify:
    - restart sing-box

- name: Ensure sing-box service is enabled
  systemd:
    name: sing-box
    enabled: yes
    state: started
