- name: apt install
  apt:
    pkg:
      - htop
      - ethtool
      - dnsutils
      - apache2-utils
      - smartmontools
      - cryptsetup
      - iotop
      - iftop
      - nmap
      - whois
      - net-tools
      - iperf3
      - mtr
      - tmux
      - ffmpeg
      - python3-dev
      - python3-pip
      - python3-venv
    state: latest
    install_recommends: no
    update_cache: yes
- name: apt upgrade
  apt:
    upgrade: safe
    install_recommends: no
    update_cache: yes
- name: pip install
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  loop:
    - pip
    - docker
    - docker-compose
    - youtube-dl
    - hvac
