- name: apt install
  apt:
    pkg:
      - ncdu
      - htop
      - ethtool
      - dnsutils
      - apache2-utils
      - smartmontools
      - cryptsetup
      - lm-sensors
      - iotop
      - iftop
      - nmap
      - whois
      - net-tools
      - iperf3
      - mtr
      - tmux
      - curl
      - wget
      - wput
      - ffmpeg
      - python3-dev
      - python3-pip
      - python3-venv
    state: present
    install_recommends: no
    update_cache: yes
  become: true
- name: apt upgrade
  apt:
    upgrade: safe
    install_recommends: no
    update_cache: yes
  become: true
- name: pip install
  pip:
    name: "{{ item }}"
    extra_args: --upgrade
  loop:
    - pip
    - docker
    - docker-compose
    - youtube-dl
