---
- name: base
  hosts:
    - htpc
  become: true
  tags: base
  tasks:
    - name: apt install
      apt:
        pkg:
          - htop
          - atop
          - ethtool
          - dnsutils
          - smartmontools
          - cryptsetup
          - iotop
          - iftop
          - iperf3
          - mtr
          - tmux
          - ffmpeg
          - python3-dev
          - python3-pip
          - python3-venv
        state: latest
        install_recommends: no
        update_cache: yes
    - name: apt upgrade
      apt:
        upgrade: safe
        install_recommends: no
        update_cache: yes
    - name: pip install
      pip:
        name: "{{ item }}"
        extra_args: --upgrade
      loop:
        - pip
        - docker
        - docker-compose
        - youtube-dl
        - hvac

- name: docker
  hosts:
    - htpc
  vars:
    docker_users:
      - "{{ ansible_user }}"
  become: true
  tags: base
  roles:
    - docker

- name: nexcloud
  hosts:
    - htpc
  tags: nexcloud
  roles:
    - nexcloud

- name: minio
  hosts:
    - htpc
  tags: minio
  roles:
    - minio_standalone
