---
- name: nexcloud
  hosts:
    - htpc
  tags: nexcloud
  roles:
    - nexcloud

- name: minio
  hosts:
    - htpc
  tags: minio
  roles:
    - minio_standalone

- name: iperf
  hosts:
    - htpc
  tags: iperf
  become: true
  roles:
    - iperf3_server
