---

- name: base
  hosts:
    - htpc
  become: true
  tags: base
  roles:
    - base

- name: docker
  hosts:
    - htpc
  become: true
  tags: docker
  roles:
    - docker

- name: nexcloud
  hosts:
    - htpc
  tags: nexcloud
  roles:
    - nexcloud

- name: droneci
  hosts:
    - htpc
  tags: droneci
  roles:
    - droneci

- name: minio
  hosts:
    - htpc
  tags: minio
  roles:
    - minio_standalone

- name: iperf
  hosts:
    - htpc
  tags: iperf
  become: true
  roles:
    - iperf3_server
