---

- name: common
  hosts:
    - htpc
  become: true
  tags: common
  roles:
    - common

- name: docker
  hosts:
    - htpc
  become: true
  tags: docker
  roles:
    - docker

- name: nexcloud
  hosts:
    - htpc
  tags: nexcloud
  roles:
    - nexcloud

- name: gitea
  hosts:
    - htpc
  tags: gitea
  roles:
    - gitea

- name: droneci
  hosts:
    - htpc
  tags: droneci
  roles:
    - droneci

- name: registry
  hosts:
    - htpc
  tags: registry
  roles:
    - docker_registry

- name: minio
  hosts:
    - htpc
  tags: minio
  roles:
    - minio_standalone

- name: iperf
  hosts:
    - htpc
  tags: iperf
  become: true
  roles:
    - iperf3_server
