---

- name: common
  hosts:
    - vpn_servers
  tags: common
  roles:
    - common
  become: true

- name: wireguard
  hosts:
    - wireguard
  roles:
    - wireguard_server
  tags: wireguard

- name: openvpn
  hosts:
    - openvpn
  roles:
    - openvpn_server
  tags: openvpn
