---

- name: base
  hosts:
    - vpn_servers
  tags: base
  tasks:
    - name: set hostname
      hostname:
        name: "{{ inventory_hostname }}"
  become: true

- name: base
  hosts:
    - vpn_servers
  tags: base
  roles:
    - base
  become: true

- name: wireguard
  hosts:
    - wireguard
  roles:
    - wireguard_server
  tags: wireguard

- name: openvpn
  hosts:
    - openvpn
  roles:
    - openvpn_server
  tags: openvpn
