- name: install wireguard
  apt:
    pkg:
      - wireguard
      - wireguard-tools
      - qrencode
    state: latest
    install_recommends: no
    update_cache: yes
  notify:
    - restart wg
  become: true

- name: sysctl
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict:
    net.ipv4.ip_forward: 1
    net.ipv6.conf.default.forwarding: 1
    net.ipv6.conf.all.forwarding: 1
    net.ipv4.conf.all.rp_filter: 1
    net.ipv4.conf.default.proxy_arp: 0
    net.ipv4.conf.default.send_redirects: 1
    net.ipv4.conf.all.send_redirects: 0
  become: true

- name: config
  template:
    dest: /etc/wireguard/{{ wireguard_server.interface_name }}.conf
    src: wg_server_conf.j2
    owner: root
    group: root
    mode: '0600'
    backup: true
  notify:
    - restart wg
  become: true

- name: start wg
  systemd:
    daemon_reload: true
    enabled: true
    name: "wg-quick@{{ wireguard_server.interface_name }}"
    state: started
  become: true

- name: client configs dir
  file:
    path: "{{ ansible_user_dir }}/wireguard-client-configs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: client configs files
  template:
    dest: "{{ ansible_user_dir }}/wireguard-client-configs/{{ item.name }}-client.conf"
    src: wg_client_conf.j2
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    backup: false
  with_items: "{{ wireguard_peers }}"
  become: false

- name: client configs qr codes
  command:
    argv:
      - "qrencode"
      - "--type=PNG"
      - "--read-from={{ ansible_user_dir }}/wireguard-client-configs/{{ item.name }}-client.conf"
      - "--output={{ ansible_user_dir }}/wireguard-client-configs/{{ item.name }}-client.png"
      - "--size=5"
      - "--level=H"
      - "--dpi=36"
  with_items: "{{ wireguard_peers }}"
  become: false
